### PR TITLE
SMS Spam Classifier Added

### PR DESCRIPTION
**Pull request by shruti-2412**

### CODE REVIEW

**Comment by shruti-2412** [comment]
@imshivamrai282 can you please add the hacktoberfest-accepted label so that the PR can be counted in hacktoberfest. 
Currently, it is showing like this:

**Comment by imshivamrai282** [comment]
Hi @shruti-2412 i have done the same.

**Comment by shruti-2412** [comment]
@imshivamrai282  Try the hacktoberfest-accepted tag. In your tag, you have not used (-) maybe that's why it is not getting accepted. And in another tag you have mentioned hacktober-accepted not hacktoberfest-accepted.

**Comment by shruti-2412** [comment]
@imshivamrai282 can you pls try adding hacktoberfest-accepted label. You have added hacktober-accepted instead and in one tag you have not used - (hyphen).

**Comment by shruti-2412** [comment]
@imshivamrai282 Thank you.

**Pull request merged**
